inherit_gem:
  syntax_tree: config/rubocop.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
